### ISSUE TITLE
Bring back the old borderless window feature

### ISSUE THREAD

**Issue by ItsPasi** [Kira-NT/cubes-without-borders#18] opened 2024-06-26 16:40 UTC
Hey, I noticed that on your current mod (2.0.1) you changed the way the borderless window works. While this does prevent the game from going black for a split second when switching to another monitor for example, this increases the games input lag. This is because the Windows Desktop has inbuilt v sync. Playing any game in windowed mode therefore turns on v sync. 

Because of that I either ask you to create another option to choose from or backport the change that has been made.

**Comment by Kira-NT** [comment] 2024-06-27 12:36
Hi! As a matter of fact, `v2.0.0` resorted to the original approach of creating a borderless fullscreen window on Windows, which was used by this mod from the very start. It was `v1.1.0` that deviated from the path I had chosen for this project, and that experiment ended horribly with countless complaints from users. An average user doesn't want their screen to flicker; an average user wants to put PiP players on top of their gameplay; and so on. An average user wants a true windowed fullscreen mode from a mod like this one.

However, I see ya. If you are a competitive player and input lag is something that worries you, and if your primary need from CWB is to prevent the game from collapsing whenever you click something on your second monitor, I can implement that for you. It's important to note that I don't want to introduce a new, separate fullscreen mode for this, as it would be a Windows-only feature. Nor do I want to create a distinct option that would alter the behavior of the added "Borderless" fullscreen mode, as, once again, that would be Windows-specific, and additionally, this would require some kind of configuration screen, which I certainly don't want to implement for a single setting.

However, I can make this into a "hidden" option, accessible via an environment variable. For example:

```properties
CWB_ENABLE_TRUE_WINDOWED_FULLSCREEN=false
```

If you use a decent launcher like Prism, it allows you to easily specify these variables on a per-instance basis or even globally.

If this solution works for you, I'll happily implement it, as it would only require about five lines of code :)

**Comment by ItsPasi** [comment] 2024-06-27 20:52
Would I be able to do this in the Modrinth launcher? But I don't think that's the best solution. Also the way it was handled in that version is how it works in most other games that have a seamless fullscreen. I think it is often directly the fullscreen mode that's just better. Sure you can't implement it that way? Would it be hard to detect if you are playing on a windows pc and then just tun it on? But as a "hidden" option or less known one I would think a command would be better since it wouldn't be dependent on launcher.

**Comment by Kira-NT** [comment] 2024-06-28 12:23
> Would I be able to do this in the Modrinth launcher?

Of course! Once again, you can do that either in the app settings *(so every instance inherits those variables)* or directly in the instance-specific settings *(so the variable is set only when you are running that specific instance)*.

> But I don't think that's the best solution.

It is not. Imperfect solutions for imperfect systems.

> Would it be hard to detect if you are playing on a windows pc and then just tun it on?

I think there's a misunderstanding here. Windows **is already** special cased. On every other platform, CWB uses what you refer to as "the fullscreen mode that's just better" - i.e., a proper fullscreen mode with one additional attribute set that tells the window not to iconify itself whenever it loses focus. However, it doesn't work properly on Windows. Because nothing ever works properly on Windows.

The current behavior is a conscious choice made to minimize the number of problems Windows users encounter with their game. It's tailored to the average user who doesn't want their display to flicker, doesn't care about input lag in a block game, and wants to put overlays and PiP windows on top of their gameplay from time to time. The issue here is that you are not that average user - you do care about input lag, so much in fact, that you are willing to make the tradeoff of having your screen flicker again. Obviously, I'm not going to change the defaults because of a very small subset of players, but I'm happy to provide means of achieving the desired behavior to those who need it.

Look, I'm not particularly happy about the current state of affairs either. I wish we didn't need to special case any platforms, and I wish this mod was as simple as `glfwSetWindowAttrib(handle, GLFW_AUTO_ICONIFY, GLFW_FALSE)`. Sadly, Windows exists. When I attempt the same approach that works perfectly on every other OS, it fails there. Specifically:

1) The window gains what the general public often calls "an exclusive fullscreen" *(some folks insist it should be called "temporal fullscreen," but this term does a very poor job of describing what actually happens here, and the terminology around these concepts is already too sloppy, so I'm not doing that)*. This means that compositing is entirely disabled for this window, preventing any overlays or other windows from rendering on top of it.
2) For some inexplicable reason *(possibly related to the exclusive fullscreen mode)*, the window starts to flicker whenever it gains/loses focus.

These problems are too severe for the average user. Just look at the number of issues v1.1.0 generated to understand why I'm not bringing that mess back.

Ultimately, I'd love to identify the root causes of these issues and make the mod behave consistently across all platforms. However, there are three potential points of failure: GLFW, your OpenGL driver, and Windows itself *(specifically, DWM)*. Until I determine which component(s) is responsible for these spectacular failures and find a way to circumvent them, it remains but a patchwork solution. And I don't really want to turn patchwork-inspired fixes into permanent solutions, such as introducing a third fullscreen mode solely for Windows users. Hence, the suggestion of using environment variables until everything here is sorted out.

> But as a "hidden" option or less known one I would think a command would be better since it wouldn't be dependent on launcher.

It's not dependent on the launcher. Environment variables are an OS-level concept. It's just that launchers may choose to simplify the process of setting them for you and/or create a somewhat sandboxed environment for your game instances to prevent the variable spillage.

**Comment by ItsPasi** [comment] 2024-06-28 22:45
I think you misunderstood what I said. I think the best option would be to change the normal fullscreen option to act as it did in the old version, since there are other games who handle it exactly like that. There would be no drawback since it's just the normal fullscreen mode but improved. I have checked other games and borderless window is handled in most games like it is in the latest version. And fullscreen is handled vastly differently from game to game, some minimize, some stay focused but have a 5sec blackscreen and some (crab champions, fortnite) do it like the old version did it. I see no issue changing the default minecraft fullscreen to act as a fullscreen where you can tab out. Especially if a game like fortnite also does it this way.

**Comment by Kira-NT** [comment] 2024-06-30 14:14
> There would be no drawback since it's just the normal fullscreen mode but improved.

We wouldn't be having this conversation if this was the case, because the whole premise of this mod is to provide a better fullscreen mode.

> I think the best option would be to change the normal fullscreen option to act as it did in the old version

Oh, I'm definitely not doing that. Replacing a perfectly fine fullscreen mode with one that causes flickers, randomly breaks some shaders (???), and does other fun stuff? Nope, this doesn't sound like "the best option" to me.

> I have checked other games and borderless window is handled in most games like it is in the latest version.

I can neither deny nor confirm this statement. I haven't used Windows for a while, but I don't think I remember my games violently flickering whenever I alt-tabbed them?

So, here are our options:

|                                            | v1.1.0 | v2.0.0 |
|:-----------------------------------|:---------:|:--------:|
| No flickering                     |     ❌     |    ✅    |
| Doesn't break shaders    |     ❌     |    ✅    |
| Allows compositing         |     ❌     |    ✅    |
| Doesn't add to input lag |     ✅     |    ❌    |

And look, I'm sorry, but the way `v2.0.0` does it (and `v1.0.0` did) just better suits the general population. Very few people care about input lag in general, even in FPS games, let alone in a block game, to justify throwing everybody else under the bus.

I would love for proper borderless fullscreen to work as it should and as it already does on other platforms, but something in the GLFW+Windows pipeline goes horribly wrong, turning it into that exclusive fullscreen legacy abomination that causes nothing but problems. Until I *hopefully* find a solution for that, I won't bring it back, especially not as a formal feature, because I don't want to turn something that should eventually be obsolete into a permanent feature.

Once again, I'm not against providing you and a few others who care so much about input lag with a way to revert to that problematic solution that happens to suit you better. I can easily do this either via environment variables or by creating a separate branch for you that turns the "Borderless" mode into the one you prefer. However, the latter will be a one-time action, as I'm not going to bother updating that branch every time I update the mod. As for the environment variable-based solution, it's easy for me to maintain it until a perfect solution for the Windows crowd is found.

**Comment by ItsPasi** [comment] 2024-06-30 17:40
> Oh, I'm definitely not doing that. Replacing a perfectly fine fullscreen mode with one that causes flickers, randomly breaks some shaders (???), and does other fun stuff? Nope, this doesn't sound like "the best option" to me.

I haven't seen any bug report talking about shaders breaking and it didn't happen on my end at least. Also flicker will happen anyway if you tab out of the normal fullscreen game. If you can reproduce the shader breaking bug I wanna see if it also happens if you just tab out/press F11 to exit the fullscreen mode manually.

> I can neither deny nor confirm this statement. I haven't used Windows for a while, but I don't think I remember my games violently flickering whenever I alt-tabbed them?

No I said borderless acts in other games like in v2.0.0. I am talking about the normal fullscreen mode of other games that acts like v1.1.0 including Fortnite. All games will flicker when you tab out of a real fullscreen mode. Just that Minecraft normally minimizes instead of staying unfocused. Also I don't encounter a "violent flicker" how you describe it, the screen simply goes black for 1 frame. But to be fair to other games, there are many that make the screen glitch for up to 10 seconds when you tab out of them. I can think of BeamNG, and GTA5.

Still if you don't want to implement it like that I still see much better options than the environment variables you talked about, since this isn't mod settings dependent but instance and launcher dependent. Meaning if I change my launcher and copy the instance, it won't work anymore and I would have to reapply, probably looking at this issue report since it probably won't be documented elsewhere.
Why not activate it via a command in mc chat? Or press a certain key combination when clicking on the borderless window option?

**Comment by Kira-NT** [comment] 2024-07-02 18:53
> I haven't seen any bug report talking about shaders breaking and it didn't happen on my end at least.

I'm talking about #14. However, to be more precise, it's about Distant Horizons with shaders, not just shaders in general.

> No I said borderless acts in other games like in v2.0.0.

I see what you're saying. That's what I'm also talking about.

> No I said borderless acts in other games like in v2.0.0. I am talking about the normal fullscreen mode of other games that acts like v1.1.0 including Fortnite. All games will flicker when you tab out of a real fullscreen mode.

I honestly don't remember that happening on a regular basis. Sure, there were games and apps that handled fullscreen quite weirdly, but I wouldn't say that most of them did; at least, not after Microsoft deprecated their Exclusive Fullscreen *(at least as a concept)* in D3D12. And, judging by the complaints from active Windows users, they don't think this is normal either.

What I know for sure is that this flickering is not really bound to happen and it can be fixed.

> Why not activate it via a command in mc chat? Or press a certain key combination when clicking on the borderless window option?

Because if I went to this length to implement this, ahem, "feature," it would be much more reasonable to implement it as a regular option at that point. If I don't want to do that, why would walking 20 extra miles convince me otherwise? This would require tangling the mod to other parts of Minecraft it's currently not exposed to *(read as "easier updatability")*, lots of new code, and non-zero maintenance costs on my side.

That's why I suggested environment variables for the time being, because this solution requires like 5 lines of code *(that don't need to be maintained at all)* on my side, and 20 extra seconds on the user's side to Ctrl+C and Ctrl+V the variable they need from the `README`. Personally, I see this as a pretty nice compromise, taking the niche nature of the requested "feature" into consideration.

> Meaning if I change my launcher [...]

So... How often do you do that? Even if you change your launcher to something that doesn't support exporting instances *(and why would you? Seems like a downgrade to me)*, you would still need to transfer settings like JVM arguments manually. Adding extra 10-20 seconds on top of that *(or even without it, to be honest)* doesn't seem like the end of the world to me.

> since it probably won't be documented elsewhere.

I literally have a tip in the `README` for KDE users on how to "fix" PiP windows on their systems globally. Of course, I would document something directly related to the mod. I didn't mean a hidden hidden option; I meant an out-of-the-way-of-regular-users-but-still-there kind of hidden option.

**Comment by Kira-NT** [comment] 2024-07-02 19:08
However, while we were engaging in polemics, I found a way to solve all the issues that the `v1.1.0` solution had on Windows, including the flickering one. So, the proper borderless fullscreen on Windows is getting its redemption arc in `v2.1.0`, which will be released in the next hour or so :)

Once again, that's why I suggested environment variables. It would have taken me literally 5 minutes to implement, which is perfectly fine for a temporary solution; that's why I was willing to do that, and you could have been using it for the past week. Of course, I didn't expect to land on a proper solution so quickly, I thought it would take a few months rather than one additional week, but I hope you see now why more involved solutions were off the table for this one.

**Closed as completed** 2024-07-02 19:15 UTC

**Comment by ItsPasi** [comment] 2024-07-02 23:17
The shader bug seems to have gotten reintroduced without fixing the input lag in the newest version. I would highly recommend unrolling the update. 
I can tell you with very high confidence that you can't fix input lag in any windowed configuration that won't flicker since any windowed variant will force v-sync on since it is integrated into the windows desktop environment. 
The shader issue also only happens when switching modes first time and not after tabbing out of the window, borderless mining also doesn't have that shader issue so I think its a mode switching problem (though not present in 2.0.0).

The only permanent solution is to keep the borderless option as it was in 2.0.0.

I would still suggest a better fullscreen mode integration, since the flicker will happen anyways, This only makes sense if u can fix that shader issue though, but it should be possible since borderless mining doesn't have the issue. Or just add the variable if you don't want to do that. It's your mod in the end.

**Comment by Kira-NT** [comment] 2024-07-05 12:23
> The shader bug seems to have gotten reintroduced

It means that something in that pipeline depends on the value of `window.isFullscreen()`. Currently, CWB reports itself as being a non-fullscreen mode because it's not the same fullscreen mode Minecraft uses. I haven't decided if it's a bug or a feature. Judging by the existence of these compatibility problems with other mods, it's more likely the former than the latter. So, thank you for informing me.

> I would highly recommend unrolling the update.

Nope. This solution finally represents the honest-to-god borderless fullscreen mode as it was meant to be played. The previous approach was more of a hack to replicate the borderless fullscreen functionality for Windows users by forcing the window into a windowed mode, which has its own problems - WDM is much less efficient at dealing with regular floating windows, and third-party apps like OBS didn't recognize the game as a fullscreen one *(because it wasn't, really)*.

So, even if an odd old bug has been resurrected by this update, I'd rather properly deal with it than resort back to hacky solutions. Also, this means that the Distant Horizons + Shaders bug has never been fixed for Linux/macOS users, as they've been using proper borderless fullscreen from the start.

> borderless mining doesn't have the issue

Borderless Mining hijacks the original fullscreen mode and alters its behavior, so it doesn't change the way the window reports on whether it's in fullscreen mode or not. For this mod, I have a distinct requirement - it adds a new fullscreen option, not overrides the original one.

> It's your mod in the end.

The problem we have here is that you are obsessed with Windows' exclusive fullscreen, which **by definition** is not borderless fullscreen. Honestly, I don't understand what this whole input lag fuss is about. Back in the days when I was into competitive FPS games, I played on a laptop with V-Sync on *(I cannot stand screen tearing)* using a wireless trackball mouse - a setup truly disastrous from the perspective of folks who try to optimize every little thing about their gameplay - but somehow, this never stopped me from holding the top ranks. So, I never understood the obsession some people tend to have with input lag, and probably never will, especially if we are talking about a block game written in Java. Unless you are playing on an underpowered rig on Windows <7 *(I believe they overhauled WDM somewhere around then)*, the added latency of dynamic context switching and enabled compositing is far less than the "lag" of your very own nervous system. You are most likely not able to even feel it, let alone act on it. So, yeah...

And while I admittedly see this whole ordeal as a simple nocebo effect, I at least can respect the sheer level of determination. So, here you go: https://github.com/Kir-Antipov/cubes-with-borders.

You complain about small amounts of added latency in a mod whose whole deal is implementing a borderless fullscreen mode. Like, that's the point. Yep, borderless fullscreen is less efficient, at least on Windows, than its exclusive fullscreen counterpart. However, the difference is so negligible, and the benefits outweigh it so much, that even Microsoft killed exclusive fullscreen for good *(once again, at least conceptually, as it still exists on Windows)* in D3D12. And this mod strives to do the same - add a fullscreen mode *most* people actually want instead of that legacy abomination we get by default. And you are unhappy about it. Because you don't actually want borderless fullscreen. You want the same old exclusive fullscreen, just without the automatic window minimization feature *(which is just a window feature, not an inherent property of this particular type of fullscreen)*. You want a "borderless fullscreen" Minecraft mod that unknowingly *(I hope)* misleads you about what it actually does and never actually delivers a borderless fullscreen experience *(there's a pretty good reason I've been asked to write this mod)*.

So, I made a mod specifically for you and folks like you. It consists literally of a single line of code, so it works for every Minecraft version ever released and is likely to work forever, and it presents you with the truest exclusive fullscreen experience possible - even dynamic context switching is disabled, so you won't be able to open windows on top of Minecraft at all, however, thanks to this, you are not going to experience the added latency of a single `if` statement within DWM related to it *(feel free to let me know, however, if this is too far and you are okay with sacrificing 1 ns to the input lag gods, so you can actually put windows on top of the game when it's unfocused)*. So, live your happily ever after with the fullscreen mode you've always desired!

**Comment by Kira-NT** [comment] 2024-07-05 12:25
P.S. - I reread my message, and without knowing the intents behind it, some parts may appear harsher than I meant them to be. So, let me clarify: while I do find your devotion to decreasing input lag in a block game pretty amusing, I don't mean to mock it - just harmlessly poke a bit of fun at something I *personally* don't find particularly meaningful. However, since it has meaning for you, I made a separate mod for you to enjoy, and that's the part I truly mean.

**Comment by ItsPasi** [comment] 2024-07-05 12:44
> The problem we have here is that you are obsessed with Windows' exclusive fullscreen, which **by definition** is not borderless fullscreen. Honestly, I don't understand what this whole input lag fuss is about. Back in the days when I was into competitive FPS games, I played on a laptop with V-Sync on _(I cannot stand screen tearing)_ using a wireless trackball mouse - a setup truly disastrous from the perspective of folks who try to optimize every little thing about their gameplay - but somehow, this never stopped me from holding the top ranks. So, I never understood the obsession some people tend to have with input lag, and probably never will, especially if we are talking about a block game written in Java. Unless you are playing on an underpowered rig on Windows <7 _(I believe they overhauled WDM somewhere around then)_, the added latency of dynamic context switching and enabled compositing is far less than the "lag" of your very own nervous system. You are most likely not able to even feel it, let alone act on it. So, yeah...

Thanks for making the other mod, I will just go on about this section for a short moment.
I don't even play competitively, all I do in Minecraft is play parkour and similar gamemodes with some friends. I just hate the feeling of lag, I want to play as closely as possible to real life. This is also why I made a motionblur mod, since reallife basically has "motionblur". I play on a 270hz display and on average v-sync adds 10-20ms of delay. I can differentiate between 3ms of delay which I confirmed in a blind A/B test. It is definitely a significant difference in lag and that's why in general a real fullscreen makes more sense. In fact I am so obsessed with it when I was active in the game osu!, I bought over 10 different tablets to find one with the lowest input lag, which btw most pro players do not even play with. And I am not even high in ranks in that game either. I just notice evey little detail that makes gameplay imperfect, playing with less lag just is more fun, no need for anything competitive.
Also screen tearing at 270hz isn't really a big deal anymore, definitely less than the input lag.

For me the reason to want this sort of mod is simple, get the benefits of fullscreen but be able to tab out of it and switch programs. If Microsoft had an option to have borderless without v sync that would be amazing but I think Windows is too stupid for it. There might be an option for it somehow, since windows in its settings has an option to "optimize windowed games" which I think turns of v-sync in some games but I have no idea how it works exactly.

**Comment by Kira-NT** [comment] 2024-07-06 14:28
> I can differentiate between 3ms of delay

My god... That's not like humanly possible. Well, okay, it depends on what you mean by "differentiate."

If you mean "recognize and act on it," it's biologically not possible. Humans are very unoptimized creatures, and I'm honestly amazed that we made it this far as a species. It takes between 100 and 200 ms, depending on the person, to react to a visual stimulus. First, the light needs to reach our eyes, then that data needs to reach our brains, where it's decoded, after that, we need to make a conscious decision on what to do with that information, and finally, all the necessary signals must propagate to our limbs in order to perform the action we decided upon, which also takes time. While we can certainly train and speed up our decision-making abilities, other than that, we are biologically limited. The only way to act on something faster than that 100-200 ms window is to react to something that hasn't happened yet, i.e., infer what comes next from the current context. Thankfully, on average, we are pretty good at that, so the numbers usually look much better in practice.

If you mean "consciously detect a difference," it's not possible either. It still takes tens of milliseconds for us to consciously process any stimulus.

However, if you mean "kind of feel the difference," then maybe. Recent *(not really)* research shows that if we strip the "conscious" component from this whole process, humans are capable of registering changes at much higher rates than we previously thought, somewhere in the 10 ms window on average. This is the sole reason why we have screens with refresh rates higher than 60 Hz. While we cannot properly see the difference, we can feel it, so, for example, 120 Hz screens are perceived as the ones providing a smoother experience, compared to the 60 Hz monitors. However, this is not something I'm ready to take seriously, as we have yet another wonderful capability as a species: we can gaslight anybody, including ourselves, into believing almost anything. So, I cannot really tell if 120 FPS feels like a smoother experience because I **genuinely feel** this way or simply because I **know** that I should feel this way.

So, maybe you did train yourself to unconsciously register the smallest things at inhuman speeds. However, given the imperfect nature of our world, I would say this is one of the most useless superpowers you could think of :D
At least you got 10 tablets out of it :D

> Also screen tearing at 270hz isn't really a big deal anymore, definitely less than the input lag.

Well, yeah, if you have a rig that's able to utilize that insane refresh rate. And I don't think most people have that.

> get the benefits of fullscreen but be able to tab out of it and switch programs.

I understand your motivation; it's just that you didn't really want borderless fullscreen to begin with :D

> since windows in its settings has an option to "optimize windowed games" which I think turns of v-sync in some games but I have no idea how it works exactly

Honestly, me neither. That's the first time I've ever heard about this feature. Windows' compositor renders floating windows as part of the core interface, so whatever graphical options it gets, the same go for regular windows, and there's no real way to separate one from another. My guess here would be in favor of system resources distribution. Processes that use regular floating windows usually share the same priority level *(unless explicitly stated otherwise either by the app or by the system administrator)*, while fullscreen apps get a bigger cut, as you are much more likely to be focused on them *(which is a more than fair assumption to make)*. So, this "optimize" feature may try to detect windowed games and automatically move them to a higher priority level, so they can hog more of the system resources and be a bit more responsive than they would otherwise be.

**Comment by ItsPasi** [comment] 2024-07-06 15:52
> However, if you mean "kind of feel the difference," then maybe. Recent _(not really)_ research shows that if we strip the "conscious" component from this whole process, humans are capable of registering changes at much higher rates than we previously thought, somewhere in the 10 ms window on average. This is the sole reason why we have screens with refresh rates higher than 60 Hz. While we cannot properly see the difference, we can feel it, so, for example, 120 Hz screens are perceived as the ones providing a smoother experience, compared to the 60 Hz monitors. However, this is not something I'm ready to take seriously, as we have yet another wonderful capability as a species: we can gaslight anybody, including ourselves, into believing almost anything. So, I cannot really tell if 120 FPS feels like a smoother experience because I **genuinely feel** this way or simply because I **know** that I should feel this way.

Well of course I mean I feel the difference. That's why its important for gameplay, no one wants to play with lag, and 100ms of delay would actually be unplayable to most people. Playing with a 100ms ping is baaaad. I attached my latency blind tests that I just did, for 3ms differences I would need to train to tell the difference again and that's too much effort, but 5ms is easy to get. 
![grafik](https://github.com/Kir-Antipov/cubes-without-borders/assets/12584747/44cdef05-fa82-4e87-a7ff-9c2a21680f68)


And about the refresh rate your are very wrong actually. Humans could theoretically differentiate even between a 10.000hz and a 20.000hz display. First of all the threshold for a smooth movement feeling (continuous image) is at around 80hz (flicker fusion frequency). This is also only applicable if certain conditions are met. One of them is motion blur. This is why I made my mod. There is something called the phantom array effect. Basically your eyes will take in any light they get so if an object moves very fast and turns off the light every now and then, you will see this gap. Even if you have a 10.000hz display you will see this gap if the light moves fast enough. How to solve this issue? Use motion blur to fill in those gaps. 
So this way even at 80/90hz the image will look perfectly smooth as long as motion blur is applied. But there is another issue with low Hz. Well, it's motion blur. According to research the amount of Hz needed to eliminate any kind of perceivable motion blur is around 1000-2000hz. You can look it up at blurbusters.com. This is why we need 1000hz+ displays to simulate human vision. The motion blur applied (or at this point we can just call it frame blending) at a 1000hz though is so minuscule that it doesn't make any visible difference anymore other than solving the phantom array effect. 
Also there are good reasons why the Apple Vision Pro has a total End to End latency of just 10ms

(From the other issue so I only have to make one comment)
> Well, it's not, really. DWM has worked this way since it was introduced with Windows 7+. For it to work differently, you would need to create a primary buffer around the floating window in question, instead of the whole desktop. I don't think Windows does this under any circumstances. At least, there's no documentation on the existence of such a feature. So, as far as I'm concerned, it doesn't exist :D

Again the program I told you about (Latency Split Test) does this. Well it might turn off v-sync for the desktop as long as nothing else is moving on it. As soon as I have a browser open with a video playing in the background v-sync turns back on. I have no idea how it works but it definitely works since you can easily tell if v-sync is on or off in that application.

**Comment by Kira-NT** [comment] 2024-07-11 16:11
> Playing with a 100ms ping is baaaad.

Couldn't agree more on that :D However, we are talking about much smaller delays here.

> I attached my latency blind tests that I just did, for 3ms differences I would need to train to tell the difference again and that's too much effort, but 5ms is easy to get.

So, you are just built different *(if the test is actually at least somewhat representative, of course)* :D These numbers are much better than those of an average person, especially the 3 ms one.

> Humans could theoretically differentiate even between a 10.000hz and a 20.000hz display.

Theoretically, there's a non-zero chance that all the particles I consist of could collectively materialize somewhere on the Moon the next time I'm observed. However, I'm only going to worry about that when I see it happen to someone with my own eyes. And currently I see people struggling to consistently differentiate between 120 Hz and 240 Hz monitors, so here's that.

I couldn't find any mentions that 10+ kHz could have any noticeable visual effects, except that a percentage of the population might observe the stroboscopic effect under very specific conditions, but that's about it.

Anyways, this looks like a such a first-world problem to me that I would prefer to see many other kinds of issues solved by our society long before we have 10 kHz monitors, just so we feel a tiniest bit better while looking at our displays. However, given the reality we live in, it's almost certainly going to end up the other way around.

> Also there are good reasons why the Apple Vision Pro has a total End to End latency of just 10ms

Isn't that quite a substantial amount by your own measure, though? That's more in line with the average unconscious perception limit I mentioned earlier, and you are more sensitive than that.

> Again the program I told you about (Latency Split Test) does this. Well it might turn off v-sync for the desktop as long as nothing else is moving on it.

I don't think the developers of the app did that. It's built using UE4 after all, and I'm pretty sure the Unreal folks know more about Windows quirks than I do and, thankfully, ever will. So, the idea that the app might disable v-sync for the entire desktop *(like an absolute gigachad)* is not entirely off the table.
