### ISSUE TITLE
1.21.1 breaks after restart

### ISSUE THREAD

**Issue by Alfie51m** [Kira-NT/cubes-without-borders#31] opened 2024-08-27 02:41 UTC
After changing my fullscreen mode to borderless it works fine until i restart my game, it still says borderless in video settings however doesn't work

**Comment by thatlittledrummerboi** [comment] 2024-09-29 15:50
it doesn't even let me choose a borderless option for me

**Comment by Kira-NT** [comment] 2024-09-29 18:32
@thatlittledrummerboi, see #30

**Comment by Kira-NT** [comment] 2024-10-29 01:18
I'm not sure if this issue occurred because something broke in the mod itself or due to compatibility issues with other mods. However, I have essentially rewritten this project from scratch and tested the new version across all available operating systems and mod loaders I could reach. As of now, the problem is not reproducible, at least anymore. Therefore, I'll be closing this as resolved. However, if you still experience this issue, please let me know and feel free to reopen it.

**Closed as completed by Kira-NT** 2024-10-29 01:18 UTC
