### ISSUE TITLE
Issue With Distant Horizons

### ISSUE THREAD

**Issue by Ysus1** [Kira-NT/cubes-without-borders#33] opened 2024-09-17 04:38 UTC
When selecting the option for borderless window, All the Distant horizon chunks are displayed over all fully rendered chunks.
![2024-09-17_16 36 56](https://github.com/user-attachments/assets/2ce3a615-e5b7-484f-ae10-aecb6ebec37f)

**Comment by Kira-NT** [comment] 2024-09-19 21:39
Hi! This is a duplicate of #14.

TL;DR: There seems to be an issue on Distant Horizons' end that causes glitches when switching from one fullscreen mode to another. To work around this, enable Borderless Fullscreen in the settings, then toggle it off and on again using F11. This should fix the issue with DH. Additionally, after restarting the game, you should also be fine, as Borderless Fullscreen is the only fullscreen mode triggered in that situation.

**Closed as not planned** 2024-09-19 21:39 UTC
