### ISSUE TITLE
Weird resolution shift when starting the game

### ISSUE THREAD

**Issue by vico93** [Kira-NT/cubes-without-borders#19] opened 2024-07-05 19:15 UTC
Using 2.1.0+1.21:

When i boot the game with fullscreen enabled, the main screen seems to reduce the resolution quickly (don't know exactly for what, but seems to be a 4:3 one), when returns to the normal (and when the game actually appear fullscreen, in Mojang logo phase), and all the other windows get shifted around due to the resolution change.

I suspect this mod because all the other games i play in fullscreen (either starting or switching to later), like Project Zomboid and some emulators, doesn't do this issue.

I'm playing in a laptop with integrated screen in 1080p with 125%dpi, meanwhile the second screen is an old one (using even a VGA to HDMI adapter), resolution at 1360x768, 100% dpi.

**Comment by Kira-NT** [comment] 2024-07-06 15:02
So, the problem arises whenever you use this mod and still use regular fullscreen *(for some reason :D)*?

This issue stems from a vanilla bug. In short, Minecraft creates a fullscreen window using the `--width` and `--height` values you specified *(if you didn't specify them, they default to `854` and `480`, respectively)* as the target display resolution. Usually, the game unscrews itself in the same frame the problem is created, and Windows is unable to react quickly enough to mess up your desktop. However, it seems the presence of this mod is enough to break that fragile balance.

I had a fix for that earlier, but I [removed it](https://github.com/Kir-Antipov/cubes-without-borders/commit/5c5f1f2f6b4ba63c9c163435ba507cb1d3f1f15f) because whenever you use borderless fullscreen, the game no longer starts in a regular fullscreen window *(it steals focus, and lots of people didn't like that)*, so the problem became irrelevant for this mod. Or so I thought.

Could you describe a bit more about how you ended up in this peculiar situation? Also, do you use the `--fullscreen` flag?

**Comment by vico93** [comment] 2024-07-06 18:18
> So, the problem arises whenever you use this mod and still use regular fullscreen _(for some reason :D)_?
> 
> This issue stems from a vanilla bug. In short, Minecraft creates a fullscreen window using the `--width` and `--height` values you specified _(if you didn't specify them, they default to `854` and `480`, respectively)_ as the target display resolution. Usually, the game unscrews itself in the same frame the problem is created, and Windows is unable to react quickly enough to mess up your desktop. However, it seems the presence of this mod is enough to break that fragile balance.
> 
> I had a fix for that earlier, but I [removed it](https://github.com/Kir-Antipov/cubes-without-borders/commit/5c5f1f2f6b4ba63c9c163435ba507cb1d3f1f15f) because whenever you use borderless fullscreen, the game no longer starts in a regular fullscreen window _(it steals focus, and lots of people didn't like that)_, so the problem became irrelevant for this mod. Or so I thought.
> 
> Could you describe a bit more about how you ended up in this peculiar situation? Also, do you use the `--fullscreen` flag?

Thanks for the clarification. I dont use any other argument to launch the launcher except `--workDir`.

**Comment by vico93** [comment] 2024-07-06 19:46
Also, seems like using `--width 1920 --height 1080` (my screen resolution) to the arguments of the non-UWP launcher (available [here](https://www.minecraft.net/en-us/download/alternative)) didnt solved the problem.

**Comment by Kira-NT** [comment] 2024-07-07 12:02
These are not launcher arguments; they are Minecraft ones, meaning the launcher needs to pass them to the game for you. I don't have the slightest clue what the Microsoft launcher looks like nowadays, but here are the respective options in Prism Launcher:

<img alt="Example" width="548.67" src="https://github.com/Kir-Antipov/cubes-without-borders/assets/40232067/369b1375-b95f-495e-9225-6567af3c71e9">

Also, just out of curiosity, why do you have this mod installed yet you continue to use regular fullscreen? It doesn't mean that it should be borked and I won't fix it *(again)*, but still.

**Comment by vico93** [comment] 2024-07-07 15:12
This mod was recommended to me after i was looking for an alternative to [Borderless Window](https://modrinth.com/mod/borderless-mining) since that one wasnt updated past 1.20.2

**Comment by vico93** [comment] 2024-07-07 15:20
Btw, just discovered a PR by @sky-is-winning to Borderless Window (via [this](https://github.com/comp500/BorderlessMining/pull/112)) that seems to work in 1.21.

One detail i noticed is that, in that mod (at least in that PR), the game always start in windowed mode (what prevent the issue that made me create this ticket), but if fullscreen was enabled last time i played it automatically switches to borderless fullscreen.

**Comment by Kira-NT** [comment] 2024-07-07 15:31
> the game always start in windowed mode

It does the same thing here. If your game starts as a fullscreen window, that means you use regular fullscreen, not the borderless one.

**Comment by sky-is-winning** [comment] 2024-07-07 16:36
> Btw, just discovered a PR by @sky-is-winning to Borderless Window (via [this](https://github.com/comp500/BorderlessMining/pull/112)) that seems to work in 1.21.
> 
> One detail i noticed is that, in that mod (at least in that PR), the game always start in windowed mode (what prevent the issue that made me create this ticket), but if fullscreen was enabled last time i played it automatically switches to borderless fullscreen.

Didn't change anything about start-up in my PR, that's an issue with the fact borderless fullscreen is essentially windowed mode only the window is the same size as your display resolution. So, Minecraft is correct thinking you were in windowed mode, because you were. Might look into if we can override that though.

**Comment by Kira-NT** [comment] 2024-07-09 17:33
> that's an issue with the fact borderless fullscreen is essentially windowed mode

That's... not really what it is *(and also not how it works)*. This was a conscious decision by comp500:

```java
	// Pretend to the constructor code (that creates the window) that it is not fullscreen
	@Redirect(method = "<init>",
		at = @At(value = "FIELD", target = "Lnet/minecraft/client/util/Window;fullscreen:Z", opcode = Opcodes.GETFIELD),
		// currentFullscreen still needs to be set correctly
		slice = @Slice(from = @At(value = "FIELD", target = "Lnet/minecraft/client/util/Window;currentFullscreen:Z", opcode = Opcodes.PUTFIELD, ordinal = 1))
	)
	public boolean constructorIsFullscreen(Window window) {
		if (ConfigHandler.getInstance().isEnabled()) {
			return false;
		}
		return fullscreen;
	}
```

Either they didn't want to deal with bugs like this one, or they were wise to assume that the borderless fullscreen crowd doesn't like their focus *(and, by extension, mouse cursor)* being stolen *(Windows is horrendous at preventing such things from happening, so I guess it's everybody else's job now)*.

> Might look into if we can override that though.

So, wouldn't actually recommend doing that.

**Comment by sky-is-winning** [comment] 2024-07-09 20:56
If you make it launch in normal fullscreen, of course it will steal focus, that's what fullscreen mode is.
My explanation was simplified. You could still make it launch in borderless mode by default.

**Comment by Kira-NT** [comment] 2024-07-10 13:52
> of course it will steal focus, that's what fullscreen mode is.

If Windows does a poor job at something, it doesn't mean that this is how things are supposed to be. Because Windows always does a poor job at virtually everything.

> You could still make it launch in borderless mode by default.

If by "launch" you mean "create a window using the fullscreen mode BM chose as its meta," then no, you can't do that either.

**Comment by sky-is-winning** [comment] 2024-07-10 15:41
i mean do what the f11 key does without the user having to press it

**Closed as completed** 2024-07-19 15:38 UTC
